### ISSUE TITLE
Move Loader into App

### ISSUE THREAD

**Issue by nitriques** [DeuxHuitHuit/framework.js#14]
- [x] Deprecated it (1.6)
- [x] Remove it (2.0)

**Comment by fhamon** [comment]
@nitriques App.loader ?

**Comment by nitriques** [comment]
@fhamon Did we do `App.Storage` or `App.storage` ?

**Comment by fhamon** [comment]
App.storage

**Comment by nitriques** [comment]
`App.loader` then.

**Comment by nitriques** [comment]
Done in b0ea980a6339301736a4271fc564fcc65e499a53
