### ISSUE TITLE
Remove device detection from the jQuery namespace

### ISSUE THREAD

**Issue by nitriques** [DeuxHuitHuit/framework.js#5]
Use App.device instead.

- [x] Introduce the new members (1.5)
- [x] Deprecate the jQuery members (1.5)
- [x] Actually remove it (2.0)

**Comment by nitriques** [comment]
@fhamon did the last part was made ?

**Comment by fhamon** [comment]
@nitriques Yep. We no longer use the jQuery Namespace.

**Comment by nitriques** [comment]
Closed in c45e6ab34b8e04c66dbd59ea9d6eedb52bba217a
