### ISSUE TITLE
window.Storage conflict

### ISSUE THREAD

**Issue by nitriques** [DeuxHuitHuit/framework.js#8]
Turns out window.Storage is defined, at least in Chrome.

Maybe consider to put everything under App ? (Loader included?)

cc @PascalPiche

**Comment by nitriques** [comment]
[ ] move to App (1.6)
[ ] remove AppStorage (2.0)
[ ] remove Storage (2.0)

**Comment by nitriques** [comment]
@fhamon this has been done right?

**Comment by fhamon** [comment]
Yes ! @nitriques

**Comment by nitriques** [comment]
closed in c45e6ab34b8e04c66dbd59ea9d6eedb52bba217a
